name: next-drupal
recipe: drupal9
config:
  webroot: web

proxy:
  appserver:
    - next-drupal-backend.lndo.site
  frontend:
    - next-drupal-frontend.lndo.site:3000

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: https://next-drupal-backend.lndo.site
  frontend:
    type: node
    build:
      - cd nextjs_drupal_basic_starter && npm install
    overrides:
      ports:
        - "3000:3000"

tooling:
  npx:
    description: "Runs npx commands"
    service: frontend
  npm:
    description: "Runs npm commands"
    service: frontend
